# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 1
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 2
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 3
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 4
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 5
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 6
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 7
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 8
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 9
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 10
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 11
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 12
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 13
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 14
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 15
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 16
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 17
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 18
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 19
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 20
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 21
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 22
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 23
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 24
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 25
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 26
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 27
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 28
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 29
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 30
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 31
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 32
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 33
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 34
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 35
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 36
# sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 37
# sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 38
# sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 39
# sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 40
# sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 41
# sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 42
# sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 43
# sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 44
# sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 45
# sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 46
# sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 47
# sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 48
# sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 49
# sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 50
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 51
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 52
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 53
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 54
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 55
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 56
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 57
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 58
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 59
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 60
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 61
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 62
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 63
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 64
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 65
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 66
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 67
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 68
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 69
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 70
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 71
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 72
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 73
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 74
sbatch -p Teach-Short --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 75
