# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 1
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 2
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 3
sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 4
sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 5
sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 6
sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 7
sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 8
sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 9
sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 10
sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 11
sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 12
sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 13
sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 14
sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 15
sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 16
sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 17
sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 18
sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 19
sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 20
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 21
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 22
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 23
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 24
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 25
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 26
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 27
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 28
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 29
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 30
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 31
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 32
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 33
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 34
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 35
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 36
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 37
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 38
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 39
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 40
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 41
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 42
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 43
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 44
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 45
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 46
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 47
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 48
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 49
# sbatch -p Teach-Standard --gres=gpu:1 -d singleton -J job_train_vqapc ./job_vqapc.sh 50
